#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
controllers:
  resource: ../src/Controller/
  type: annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin



